export let hospitals = [
  {
    name: "Mount Alvernia Hospital",
    phoneNumber: "6347 6688",
    openTime: "Open 24 Hours",
    coordinates: [1.342, 103.838],
    address: "820 Thomson Rd, Singapore 574623",
    addressLines: ["820 Thomson Rd, Singapore 574623"],
    description:
      "Mount Alvernia Hospital is a 319-bed general acute care hospital with tertiary medical capabilities and two multi-disciplinary medical specialist centres in Thomson Road, Singapore. It is the only not-for-profit, private Catholic missionary hospital.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "319",
    rating: "3.6",
    website: "https://mtalvernia.sg/",
  },

  {
    name: "Thomson Medical Centre",
    phoneNumber: "6250 2222",
    openTime: "Open 24 Hours",
    coordinates: [1.3253, 103.8415],
    address: "339 Thomson Rd, Singapore 307677",
    addressLines: ["339 Thomson Rd, Singapore 307677"],
    description:
      "Thomson Medical Centre Limited is a 190-bed private hospital located at Thomson Road in Singapore. The hospital specialises in gynaecology and in vitro fertilisation. Thomson Medical Centre runs a 24-hour outpatient family clinic, as well as a range of specialist clinics.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "190",
    rating: "4,2",
    website: "https://www.thomsonmedical.com/",
  },

  {
    name: "Mount Elizabeth Hospital",
    phoneNumber: "6737 2666",
    openTime: "Open 24 Hours",
    coordinates: [1.3053, 103.8355],
    address: "3 Mount Elizabeth, Singapore 228510",
    addressLines: ["3 Mount Elizabeth, Singapore 228510"],
    description:
      "Mount Elizabeth Hospital, known colloquially as Mount E, is a 345-bed private hospital in Singapore operated by Parkway Health. Construction began in 1976 and the hospital officially opened on 8 December 1979. The hospital specialises in cardiology, oncology, and neuroscience, among other tertiary services.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "345",
    rating: "4.0",
    website:
      "https://www.mountelizabeth.com.sg/about-us/mount-elizabeth-orchard",
  },

  // {
  //     "name": "Johns Hopkins Hospital",
  //     "phoneNumber":"6880 2222",
  //     "openTime" : "-",
  //     "coordinates": [1.3212, 103.8437],
  //     "address":"11 Jln Tan Tock Seng, Singapore 308433",
  //     "addressLines":["11 Jln Tan Tock Seng, Singapore 308433"],
  //     "description": "The Johns Hopkins Hospital (JHH) is the teaching hospital and biomedical research facility of the Johns Hopkins School of Medicine, located in Baltimore, Maryland, U.S",
  //     "pincode": "110062",
  //     "zipCode":"110062",
  //     "numBeds" : "-",
  //     "rating" : "3.3",
  //     "website":"-"
  // },

  {
    name: "Gleneagles Hospital",
    phoneNumber: "6473 7222",
    openTime: "Open 24 Hours",
    coordinates: [1.306745, 103.816715],
    address: "6A Napier Rd, Singapore 258500",
    addressLines: ["6A Napier Rd, Singapore 258500"],
    description:
      "Gleneagles Hospital is a private hospital on Napier Road, Singapore next to Napier MRT station. It provides medical and surgical services. It is part of Parkway Pantai, itself a subsidiary of the Malaysian–Singaporean private healthcare group IHH Healthcare.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "258",
    rating: "3.7",
    website: "https://www.gleneagles.com.sg/",
  },

  {
    name: "Raffles Hospital",
    phoneNumber: "6311 2222",
    openTime: "Open 24 Hours",
    coordinates: [1.3011, 103.8548],
    address: "585 North Bridge Road Raffles Hospital, 188770",
    addressLines: ["585 North Bridge Road Raffles Hospital, 188770"],
    description:
      "Raffles Hospital is a tertiary care private hospital of the Raffles Medical Group, a private healthcare provider in Singapore.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "380",
    rating: "2.9",
    website: "https://www.rafflesmedicalgroup.com/services/hospital/",
  },

  {
    name: "Parkway East Hospital",
    phoneNumber: "6377 3737",
    openTime: "Open 24 Hours",
    coordinates: [1.3152, 103.9068],
    address: "321 Joo Chiat Pl, Singapore 427990",
    addressLines: ["321 Joo Chiat Pl, Singapore 427990"],
    description:
      "Parkway East Hospital is a 143-bed private healthcare facility located at the junction of Joo Chiat Place and Telok Kurau Road in Telok Kurau, in the East side of Singapore.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "106",
    rating: "3.1",
    website: "https://www.parkwayeast.com.sg/",
  },

  {
    name: "Farrer Park Hospital",
    phoneNumber: "6363 1818",
    openTime: "Open 24 Hours",
    coordinates: [1.313, 103.852],
    address: "1, #02-01 Farrer Park Station Rd, Connexion, 217562",
    addressLines: ["1, #02-01 Farrer Park Station Rd, Connexion, 217562"],
    description:
      "Farrer Park Hospital is a private tertiary healthcare institution in Farrer Park, Singapore. Located above the Farrer Park MRT station at the Connexion building, the hospital has a capacity of 220 beds across four inpatient suites and 18 operating theaters including major surgery, cardiovascular and endoscopic suites",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "121",
    rating: "3.3",
    website: "https://www.farrerpark.com/",
  },

  {
    name: "Khoo Teck Puat Hospital",
    phoneNumber: "6555 8000",
    openTime: "Open 24 Hours",
    coordinates: [1.4248, 103.838],
    address: "90 Yishun Central, Singapore 768828",
    addressLines: ["90 Yishun Central, Singapore 768828"],
    description:
      "Khoo Teck Puat Hospital is a 795-bed general and acute care hospital located at Yishun in Singapore. Named after Singaporean hotelier, Khoo Teck Puat, the hospital is part of an integrated development together with the adjoining Yishun Community Hospital.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "795",
    rating: "3.2",
    website: "https://www.ktph.com.sg/",
  },

  {
    name: "SengKang General Hospital",
    phoneNumber: "6930 5000",
    openTime: "Open 24 Hours",
    coordinates: [1.3955, 103.8934],
    address: "110 Sengkang E Way, Singapore 544886",
    addressLines: ["110 Sengkang E Way, Singapore 544886"],
    description:
      "Sengkang General Hospital is one of Singapore's public hospitals. The 1000-bed hospital opened its doors on 18 August 2018 and serves mainly the population of northeast Singapore, in particular Sengkang, Punggol, Hougang and Pasir Ris.The hospital is managed by Sengkang Health.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "1000",
    rating: "2.8",
    website: "https://www.skh.com.sg/",
  },

  {
    name: "Changi General Hospital",
    phoneNumber: "6788 8833",
    openTime: "Open 24 Hours",
    coordinates: [1.3402, 103.9496],
    address: "2 Simei Street 3, Singapore 529889",
    addressLines: ["2 Simei Street 3, Singapore 529889"],
    description: "",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "409",
    rating: "3.5",
    website: "https://www.rafflesmedicalgroup.com/services/hospital/",
  },

  {
    name: "National Neuroscience Institute",
    phoneNumber: "6788 8833",
    openTime: "Open 24 Hours",
    coordinates: [1.3221, 103.8456],
    address: "11 Jln Tan Tock Seng, Level 1, Singapore 308433",
    addressLines: ["11 Jln Tan Tock Seng, Level 1, Singapore 308433"],
    description:
      "Changi General Hospital is a 1000-bed hospital located in Simei, eastern Singapore. It is Singapore's first purpose-built general hospital to serve communities in the east and north-east regions.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "1000",
    rating: "2.9",
    website: "http://www.cgh.com.sg/",
  },
  {
    name: "Tan Tock Seng Hospital",
    phoneNumber: "6256 6011",
    openTime: "Open 24 Hours",
    coordinates: [1.3214, 103.8458],
    address: "11 Jln Tan Tock Seng, Singapore 308433",
    addressLines: ["11 Jln Tan Tock Seng, Singapore 308433"],
    description:
      "Tan Tock Seng Hospital is a tertiary referral hospital in Singapore, located in Novena. The hospital has 45 clinical and allied health departments, 16 specialist centres and is powered by more than 8,000 healthcare staff.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "1700",
    rating: "3.5",
    website: "https://www.ttsh.com.sg/",
  },
  {
    name: "KK Women's and Children's Hospital",
    phoneNumber: "6225 5554",
    openTime: "Open 24 Hours",
    coordinates: [1.3106, 103.8468],
    address: "100 Bukit Timah Rd, Singapore 229899",
    addressLines: ["100 Bukit Timah Rd, Singapore 229899"],
    description:
      "KK Women's and Children's Hospital is the largest hospital specialising in healthcare for women and children in Singapore, located at 100 Bukit Timah Road in Kampong Java, within the planning area of Kallang.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "830",
    rating: "3.2",
    website: "https://www.kkh.com.sg/",
  },
  {
    name: "National Skin Centre",
    phoneNumber: "6350 6666",
    openTime: "Opens from 8am - 5pm. Close on Saturday and Sunday",
    coordinates: [1.3198, 103.8491],
    address: "1 Mandalay Rd, Singapore 308205",
    addressLines: ["1 Mandalay Rd, Singapore 308205"],
    description:
      "The National Skin Centre (NSC) is an outpatient specialist dermatological centre with a team of dermatologists who have the experience and expertise to treat all skin conditions. It handles a patient load of about 1,000 patients daily.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "-",
    rating: "2.7",
    website: "https://www.nsc.com.sg/",
  },
  {
    name: "Singapore National Eye Centre",
    phoneNumber: "6227 7255",
    openTime: "Opens from 830am - 530pm. Close on Sunday",
    coordinates: [1.2809012, 103.8335295],
    address: "11 Third Hospital Ave, Singapore 168751",
    addressLines: ["11 Third Hospital Ave, Singapore 168751"],
    description: "",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "-",
    rating: "3.2",
    website: "https://www.snec.com.sg/",
  },
  {
    name: "Singapore General Hospital",
    phoneNumber: "6222 3322",
    openTime: "Open 24 Hours",
    coordinates: [1.2804, 103.8348],
    address: "11 Third Hospital Ave, Singapore 168751",
    addressLines: ["11 Third Hospital Ave, Singapore 168751"],
    description:
      "Singapore General Hospital is an academic health science centre as well as a tertiary referral hospital in Singapore, located next to the Bukit Merah and Chinatown districts of the Central Region.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "2000",
    rating: "3.4",
    website: "https://www.sgh.com.sg/",
  },
  {
    name: "National Cancer Centre Singapore",
    phoneNumber: "6436 8088",
    openTime: "Opens from 830am - 530pm. Close on Sunday",
    coordinates: [1.2792626, 103.834443],
    address: "11 Hospital Cres, Singapore 169610",
    addressLines: ["11 Hospital Cres, Singapore 169610"],
    description: "",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "425",
    rating: "4.0",
    website: "https://www.nccs.com.sg/",
  },
  {
    name: "National Heart Centre",
    phoneNumber: "6704 8000",
    openTime: "Opens from 8am - 5pm. Close on Sunday",
    coordinates: [1.2785753, 103.8339197],
    address: "5 Hospital Dr, Singapore 169609",
    addressLines: ["5 Hospital Dr, Singapore 169609"],
    description:
      "The National Heart Centre Singapore (NHCS) is a national and regional referral centre for cardiovascular diseases. Established in 1998, NHCS is the pioneer in cardiovascular care in Singapore.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "185",
    rating: "4.2",
    website: "https://www.nhcs.com.sg/",
  },

  {
    name: "Alexandra Hospital",
    phoneNumber: "6472 2000",
    openTime: "Open 24 Hours",
    coordinates: [1.2866, 103.8013],
    address: "378 Alexandra Rd, Singapore 159964",
    addressLines: ["378 Alexandra Rd, Singapore 159964"],
    description:
      "Alexandra Hospital is a hospital in Queenstown, Singapore providing acute and community care under the National University Health System. The hospital's colonial-style buildings were constructed in the late 1930s on 110,000 square metres of land.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "300",
    rating: "4.1",
    website: "https://www.ah.com.sg/",
  },
  {
    name: "National Univeristy Hospital",
    phoneNumber: "6779 5555",
    openTime: "Open 24 Hours",
    coordinates: [1.2939, 103.7831],
    address: "5 Lower Kent Ridge Rd, Singapore 119074",
    addressLines: ["5 Lower Kent Ridge Rd, Singapore 119074"],
    description:
      "The National University Hospital is a tertiary referral hospital in Singapore, located in Kent Ridge.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "1239",
    rating: "3.4",
    website: "http://www.nuh.com.sg/Pages/Home.aspx",
  },
  {
    name: "Ng Teng Fong General Hospital",
    phoneNumber: "6716 2000",
    openTime: "Open 24 Hours",
    coordinates: [1.3337448, 103.7432028],
    address: "1 Jurong East Street 21, Singapore 609606",
    addressLines: ["1 Jurong East Street 21, Singapore 609606"],
    description:
      "Ng Teng Fong General Hospital is a 700-bed hospital located in Jurong East, Singapore. Named after Singaporean late entrepreneur, Ng Teng Fong, the hospital is part of an integrated development together with the adjoining Jurong Community Hospital.",
    pincode: "110062",
    zipCode: "110062",
    numBeds: "700",
    rating: "2.3",
    website: "https://www.ntfgh.com.sg/",
  },
];
